### ISSUE TITLE
Gears not clear

### ISSUE THREAD

**Issue by laurens-otter** [BuildSomeStuff/CompactRoboticArm#1]
Hai, love your project and would love to try to rebuild it and control it using raspberry pi. but i cannot find anywhere which type of gears are used with the servo? Thanks in advance

**Comment by BuildSomeStuff** [comment]
Hello! I have now linked all parts (including the gears) in the video's description.

**Comment by BuildSomeStuff** [comment]
Hello! I have now linked all parts (including the gears) in the video's description.
